// prettier-ignore
// Remember, the separator between parameters is ";", not ",". I lost 6 hours because of it.
const language = {
  app_name: 'Note',
  onboarding: {
    welcome: {
      title: 'Welcome to $t(app_name)',
      description: 'Explore $t(app_name), your new digital haven for thoughts and reminders. Enjoy the simplicity and joy of note-taking redefined.',
    },
    noti: {
      title: 'Stay Updated with Notifications',
      description: 'Never miss a critical update or reminder with our timely notifications. Keep your productivity on track effortlessly.',
    },
    sync: {
      title: 'Sync Your Notes Across Devices',
      description: 'Elevate your note-taking experience with cross-device synchronization. Access your notes anywhere, keeping them safe and updated.',
    },
  },
  tag_init: {
    title: 'Select Your Own Tags',
    description: 'Kickstart your note-taking journey by creating personalized tags. These tags will help you categorize and retrieve your notes with ease.',
    helper: 'Select any tag below or create them later.',
  },
  get_start: 'Get started',
  next: 'Next',
  skip: 'Skip',
  open_private: 'Open private',
  pin: 'Pin',
  unPin: 'Unpin',
  hide: 'Hide',
  remove: 'Remove',
  delete: 'Delete',
  remind: 'Remind',
  unlock: 'Unlock',
  lock: 'Lock',
  detail: 'Detail',
  title: 'Title',
  detail_info: 'Detail info',
  content_for_note: 'Content for note',
  repeat_password: 'Repeat password',
  password: 'Password',
  enter_password: 'Enter password',
  forgot_password: 'Forgot password',
  ok: 'OK',
  private_note: 'Private notes',
  cancel: 'Cancel',
  confirm_delete: 'Confirm delete',
  repeat: 'Repeat',
  notify_after: 'Notify after {{value, duration}}',
  notify_send_after: 'Notification will be send after {{value, duration}}',
  fail_reminder: `Fail to create reminder`,
  theme: 'Theme',
  setting: 'Setting',
  color: 'Color',
  color_scheme: 'Color scheme',
  column_of_note: 'Columns of note',
  auto: 'Auto',
  light: 'Light',
  dark: 'Dark',
  follow_system: 'Follow system', 
  num_column_one: '{{count}} column',
  num_column_other: '{{count}} columns',
  edit: 'Edit',
  restore: 'Restore',
  change: 'Change',
  turn_off: 'Turn off',
  selection_zero: 'None selected',
  selection_one: '{{count}} selected',
  selection_other: '{{count}} selecteds',
  none: 'None',
  daily: 'Daily',
  weekly: 'Weekly',
  repeat_mode: '{{mode, map(none: None; daily: Daily; weekly: Weekly;)}}',
  add_tag: 'Add tag',
  notelist_empty: {
    title:  'There are no notes',
    description: "You haven't created any notes yet!",
  },
  taglist_empty: {
    title: 'There are no tags',
    description: "You haven't created any tags yet!",
  },
  create_at: 'Create at:',
  update_at:'Last update:',
  set: 'Set',
  reset: 'Reset',
  private_setting:"Private settings",
  create_tag: "Create tag",
  tag_name: 'Tag name',
  tag_label: 'Tag',
  trash: 'Trash',
  change_password: 'Change password',
  date_time: '{{value, datetime(dateStyle: medium; timeStyle: short; hour12: false;)}}',
  relative_time: "{{value, relativetime}}",
  home_hided_toast_message: 'Notes have been hidden. Pull down and hold to activate private space.',
  home_confirm_delete_description: 'Confirm deletion of this note.',
  private_confirm_delete_description: 'Private notes will not be moved to trash. Confirm to permanently delete this note.',
  tag_manager_confirm_delete_description: 'Confirm deletion of this tag.',
  trash_confirm_delete_description: 'Confirm deletion of this note.',
  use_biometric: "Biometric",
  use_biometric_desc: "Use biometrics to access private space instead of password.",
  use_password: 'Password',
  use_password_desc: "Require password each time you access private space.",
  use_bio_to_active: "Use biometric to active",
  search: 'Search',
  add_new_item:'Add new item',
  add_new_note: "Add new note",
  add_new_task: 'Add new task',
  all: 'All',
  manager: 'Manager',
  error_add_biometric: 'Something went wrong!',
  language: 'Language',
  color_scheme_label: '{{colorScheme, map(light: Light; dark: Dark; default: Auto;)}}',
  language_label: '{{key, map(en: English; vi: Vietnamese; default: Auto;)}}',
  require_permission_description: "Notification permission is required to set reminder",
  notification_toast_message: "You don't has notification permission to set reminder",
  grant: 'Grant',
  list_type: 'List type',
  sort: 'Sort',
  list: 'List',
  sort_type_label: '{{value, map(create: Created date; update: Updated date; defaut: Default;)}}',
  create_password: 'Create password',
  init_tags: 'Work,Family,Health,Goals,Study,Hobbies,Travel,Finance,Technology,Food,Books,Movies,Sports,Shopping,Important',
  go_back: 'Go back',
  create_new_note: 'Create new note',
  create_new_task: 'Create new task',
  tag_manager: 'Tag manager',
  select_tag: 'Select tag',
  task_list: 'Task list',
  set_reminder: 'Set reminder',
  reminder: "Reminder",
  clear: 'Clear',
  check: 'check',
  uncheck: 'uncheck',
  add_new_tag: 'Add new tag',
  more_action: 'More actions'
}

export default language

export type TranslationKeys = typeof language
