import { TranslationKeys } from './en'

// prettier-ignore
const language: Partial<TranslationKeys> = {
  app_name: 'Note',
  onboarding: {
    welcome: {
      title: 'Chào mừng đến với $t(app_name)',
      description: 'Khám phá $t(app_name), thiên đường số mới của bạn cho những ý tưởng và lời nhắc. Tận hưởng sự đơn giản và niềm vui của việc ghi chú được định nghĩa lại.',
    },
    noti: {
      title: 'Cập nhật thông báo mới nhất',
      description: 'Không bao giờ bỏ lỡ một cập nhật quan trọng hoặc lời nhắc với thông báo kịp thời của chúng tôi. Giữ năng suất của bạn trên đường một cách dễ dàng.',
    },
    sync: {
      title: 'Đồng bộ ghi chú của bạn trên các thiết bị',
      description: 'Nâng cao trải nghiệm ghi chú của bạn với việc đồng bộ hóa trên các thiết bị. Truy cập ghi chú của bạn ở bất cứ đâu, giữ chúng an toàn và được cập nhật.',
    },
  },
  tag_init: {
    title: 'Chọn thẻ của riêng bạn',
    description: 'Khởi động hành trình ghi chú của bạn bằng cách tạo các thẻ cá nhân hóa. Những thẻ này sẽ giúp bạn phân loại và lấy lại ghi chú dễ dàng.',
    helper: 'Chọn bất kỳ thẻ nào bên dưới hoặc tạo chúng sau.',
  },
  get_start: 'Bắt đầu',
  next: 'Tiếp theo',
  skip: 'Bỏ qua',
  open_private: 'Mở ghi chú riêng tư',
  pin: 'Ghim',
  unPin: 'Bỏ ghim',
  hide: 'Ẩn',
  remove: 'Gỡ bỏ',
  delete: 'Xóa',
  remind: 'Nhắc nhở',
  unlock: 'Mở khóa',
  lock: 'Khóa',
  detail: 'Chi tiết',
  title: 'Tiêu đề',
  detail_info: 'Thông tin chi tiết',
  content_for_note: 'Nội dung cho ghi chú',
  repeat_password: 'Nhập lại mật khẩu',
  password: 'Mật khẩu',
  enter_password: 'Nhập mật khẩu',
  forgot_password: 'Quên mật khẩu',
  ok: 'Đồng ý',
  private_note: 'Ghi chú riêng tư',
  cancel: 'Hủy',
  confirm_delete: 'Xác nhận xóa',
  repeat: 'Lặp lại',
  notify_after: 'Thông báo sau {{value, duration}}',
  notify_send_after: 'Thông báo sẽ được gửi đến bạn sau {{value, duration}}',
  fail_reminder: 'Đặt thông báo thất bại',
  theme: 'Chủ đề',
  setting: 'Cài đặt',
  color: 'Màu sắc',
  color_scheme: 'Giao diện',
  column_of_note: 'Cột ghi chú',
  auto: 'Tự động',
  light: 'Sáng',
  dark: 'Tối',
  follow_system: 'Theo hệ thống',
  num_column_one: '{{count}} cột',
  num_column_other: '{{count}} cột',
  edit: 'Chỉnh sửa',
  restore: 'Khôi phục',
  change: 'Thay đổi',
  turn_off: 'Tắt',
  selection_zero: 'Chưa lựa chọn',
  selection_one: 'Đã chọn {{count}} mục',
  selection_other: 'Đã chọn {{count}} mục',
  none: 'Không lặp',
  daily: 'Hàng ngày',
  weekly: 'Hàng tuần',
  repeat_mode: '{{mode, map(none: Không lặp; daily: Hàng ngày; weekly: Hàng tuần;)}}',
  add_tag: 'Gắn thẻ',
  home_hided_toast_message: 'Ghi chú đã bị ẩn. Kéo xuống và giữ để kích hoạt không gian riêng tư.',
  home_confirm_delete_description: 'Xác nhận xóa ghi chú này.',
  private_confirm_delete_description: 'Ghi chú riêng tư sẽ không được chuyển vào thùng rác. Xác nhận để xóa vĩnh viễn ghi chú này.',
  tag_manager_confirm_delete_description: 'Xác nhận xóa thẻ này.',
  trash_confirm_delete_description: 'Xác nhận xóa ghi chú này.',
  notelist_empty: {
    title: 'Không có ghi chú nào',
    description: "Bạn chưa tạo bất kỳ ghi chú nào!",
  },
  taglist_empty: {
    title: 'Không có thẻ nào',
    description: "Bạn chưa tạo bất kỳ thẻ nào!",
  },
  create_at: 'Tạo:',
  update_at: 'Cập nhật lần cuối:',
  date_time: '{{value, datetime(dateStyle: medium; timeStyle: short; hour12: false;)}}',
  relative_time: "{{value, relativetime}}",
  set: 'Đặt',
  reset: 'Đặt lại',
  private_setting: 'Cài đặt riêng tư',
  create_tag: 'Tạo thẻ',
  tag_name: 'Tên thẻ',
  tag_label: 'Thẻ',
  trash: 'Thùng rác',
  change_password: 'Đổi mật khẩu',
  use_biometric: 'Vân tay',
  use_biometric_desc: 'Dùng vân tay để truy cập thay vì mật khẩu',
  use_password: 'Mật khẩu',
  use_password_desc: 'Yêu cầu mật khẩu để truy cập không gian riêng tư.',
  search: 'Tìm kiếm',
  use_bio_to_active: 'Sử dụng vân tay để kích hoạt',
  add_new_item: 'Thêm nhiệm vụ mới',
  all: 'Tất cả',
  manager: 'Quản lí',
  language: 'Ngôn ngữ',
  color_scheme_label: '{{colorScheme, map(light: Sáng; dark: Tối; default: Tự động;)}}',
  language_label: '{{key, map(en: Tiếng Anh; vi: Tiếng Việt; default: Tự động)}}',
  require_permission_description: "Cần cấp quyền gửi thông báo để đặt nhắc nhở",
  notification_toast_message: "Không có quyền gửi thông báo",
  grant: 'Cấp quyền',
  list_type: 'Kiểu danh sách',
  sort: 'Sắp xếp',
  list: 'Danh sách',
  sort_type_label: '{{value, map(create: Ngày tạo; update: Ngày chỉnh sửa; defaut: Mặc định;)}}',
  create_password: 'Tạo mật khẩu',
  init_tags: 'Công việc,Gia đình,Sức khỏe,Mục tiêu,Học tập,Sở thích,Du lịch,Tài chính,Công nghệ,Thực phẩm,Sách,Phim ảnh,Thể thao,Mua sắm,Quan trọng'
};

export default language
